# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Base VM OS configuration.
    config.vm.box = "ubuntu/bionic64"
    config.vm.synced_folder '.', '/vagrant', disabled: true
    config.ssh.insert_key = false
  
    config.vm.provider :virtualbox do |v|
      v.memory = 512
      v.cpus = 1
      v.linked_clone = true
    end
  
    # Define three VMs with static private IP addresses.
    boxes = [
      { :name => "vm", :ip => "192.168.10.11" }
    ]

    # Provision each of the VMs.
    boxes.each do |opts|
      config.vm.define opts[:name] do |config|
        config.vm.hostname = opts[:name]
        config.vm.network :private_network, ip: opts[:ip]
        config.vm.provision "ansible" do |ansible|
          ansible.playbook = "provision.yml"
          ansible.inventory_path = "inventory"
          # (cf. https://github.com/ansible/ansible/issues/16259)
          ansible.raw_ssh_args = ['-o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey,keyboard-interactive']
        end
      end
    end
end
