# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.synced_folder '.', '/vagrant', disabled: true
    config.ssh.insert_key = false
  
    config.vm.provider :virtualbox do |v|
      v.memory = 256
      v.cpus = 1
      v.linked_clone = true
    end
  
    # Define three VMs with static private IP addresses.
    boxes = [
      { :name => "secure-srv", :ip => "192.168.10.2" },
      { :name => "caller",     :ip => "192.168.10.3" }
    ]
  
    # Provision each of the VMs.
    boxes.each do |opts|
      config.vm.define opts[:name] do |config|
        config.vm.hostname = opts[:name]
        config.vm.network :private_network, ip: opts[:ip]
        # Provision all the VMs using Ansible after last VM is up.
        if opts[:name] == "caller" 
          config.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbooks/provision.yml"
            ansible.inventory_path = "inventory"
            # ansible.ask_vault_pass = true
            ansible.limit = "all"
          end
        end
      end
    end
end
